context : "Engine"
LTP     : Compiler
layers  : AnythingGoes


dependencies {
	// Language Platform Layer
	LP
}


alias {
	OS      : LP.OS
	Win32   : LP.Win32
}


units {
	Config     : uf
	Cycler     : uf
	Execution  : uf			
	Engine     : uf
	Input      : uf
	Intro      : uf
	Memory     : uf
	Renderer   : uf
	State      : uf
	Timing     : uf
}

order {
	Config
	Types
	Util
	Math
	Platform
	Memory
	Timing	
	Engine
	Input
	Renderer
	State
	Intro
	Execution
}

// entrypoint : Entrypoint
